spring.application.name=nto-erp-api

# Config PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ntobase
spring.datasource.username=jou
spring.datasource.password=J9198k25
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Config do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Flyway - Configuração Forçada
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.ignore-migration-error=true
spring.flyway.baseline-version=0

# Garante que o Flyway rode ANTES do Hibernate tentar validar as entidades
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Opcional: Para ver o log detalhado do Flyway no console
logging.level.org.flywaydb=DEBUG

#Console
spring.jpa.show-sql=true

#Security
# Configurações do Spring Security OAuth2 / Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-gsgz858m42tl4kb6.us.auth0.com/

# Identificador da sua API cadastrada no Auth0 (Audience)
spring.security.oauth2.resourceserver.jwt.audiences=https://dev-gsgz858m42tl4kb6.us.auth0.com/api/v2/

